"""add_is_admin_to_users

Revision ID: 1b0a8793e991
Revises: 06a62eda3ddb
Create Date: 2025-10-13 10:18:21.945414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0a8793e991'
down_revision: Union[str, Sequence[str], None] = '06a62eda3ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # まずnullable=Trueでカラムを追加
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # 既存レコードにデフォルト値を設定
    op.execute('UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL')
    # NOT NULL制約を追加
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
