"""Addmissing tables: users , tags, user_tags

Revision ID: 6f1434563960
Revises: 9e1f0f6efe35
Create Date: 2025-10-13 03:35:54.660191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1434563960'
down_revision: Union[str, Sequence[str], None] = '9e1f0f6efe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
